require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RN_RestaurantsApp_with_Maps' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'RN_RestaurantsApp_with_MapsTests' do
    inherit! :complete
    # Pods for testing
  end
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RN_RestaurantsApp_with_Maps-tvOS' do
  # Pods for RN_RestaurantsApp_with_Maps-tvOS

  target 'RN_RestaurantsApp_with_Maps-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
